#!/usr/bin/env Rscript

#============================
### Parse input arguments ###
#============================
argsAll <- commandArgs(trailingOnly=FALSE)
Rscriptfile <- gsub("^--file=", "", grep("^--file=", argsAll, value=T))
args <- commandArgs(trailingOnly=TRUE)
if (length(args) < 3) {
	message("\nUsage:")
# 	message("Rscript ",Rscriptfile," inputdirectory configfile outputdirectory\n")
	message("aneufinder inputdirectory configfile outputdirectory\n")
	quit(save='no')
} else {
	inputfolder <- args[1]
	configfile <- args[2]
	outputfolder <- args[3]
}
if (!file.exists(configfile)) {
	message("Error: Cannot open configuration file ",configfile)
	quit(save='no')
}

#=====================
### Load libraries ###
#=====================
message("Loading libraries ...", appendLF=F); ptm <- proc.time()
suppressPackageStartupMessages(library(aneufinder))
time <- proc.time() - ptm; message(" ",round(time[3],2),"s")

#===========
### Main ###
#===========
easyAneufinder(inputfolder, configfile, outputfolder)
